---
- name: Check existence of fonts dir
  stat:
    path: "/tmp/fonts"
  register: powerline_fonts
  tags:
    - shell
    - always

# Install powerline fonts
- name: clone powerline fonts repo
  ansible.builtin.git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: /tmp/fonts
  # when: not powerline_fonts.stat.exists
  tags:
    - shell
    - always

# install fonts
- name: install powerline fonts
  ansible.builtin.shell: /tmp/fonts/install.sh
  # when: not powerline_fonts.stat.exists
  tags:
    - shell
    - always

# tasks file for oh-my-zsh
- name: Check existence of oh-my-zsh directory
  stat:
    path: "~/.oh-my-zsh"
  register: oh_my_stats
  tags:
    - shell
    - always

- name: Fetch oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install-oh-my-zsh.sh
    mode: 0755
  # when: not oh_my_stats.stat.exists
  tags:
    - shell
    - always

- name: Install oh-my-zsh
  command: zsh /tmp/install-oh-my-zsh.sh
  # when: not oh_my_stats.stat.exists
  tags:
    - shell
    - always

- name: Copy shell config
  ansible.builtin.copy:
    src: zsh/zshrc
    dest: ~/.zshrc
    owner: "{{ ansible_user_id }}"
    mode: '0644'
  tags:
    - shell
    - always

- name: Copy p10k config
  ansible.builtin.copy:
    src: zsh/p10k.zsh
    dest: ~/.p10k.zsh
    owner: "{{ ansible_user_id }}"
    mode: '0644'
  tags:
    - shell
    - always

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    force: true
  tags:
    - shell
    - always

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
    force: true
  tags:
    - shell
    - always
