---
# tasks file for pre-config
- name: Install brew package(s)
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  async: 45
  poll: 0
  with_items: "{{ brew_install }}"
  tags:
    - brew

- name: Remove brew package(s)
  community.general.homebrew:
    name: "{{ item }}"
    state: absent
  async: 45
  poll: 0
  with_items: "{{ brew_uninstall }}"
  tags:
    - brew
