# Create base dir env
- name: Create base dirs
  ansible.builtin.file:
    path: ~/Documents/{{ item }}
    state: directory
    mode: '0755'
  with_items:
    - dev
    - temp
    - study
    - work
  tags:
    - base_dirs
    - always

- name: Create work dirs
  ansible.builtin.file:
    path: ~/{{ item }}
    state: directory
    mode: '0755'
  with_items:
    - .config
    - .kube
    - dev
    - temp
    - work
  tags:
    - base_dirs
    - always
  when: ansible_architecture == "arm64"
