---
- name: Install latest available neovim version
  community.general.homebrew:
    name: "neovim"
    state: present
  tags:
    - always
  async: 300
  poll: 0

# install homebrew packages
- name: Install brew package(s)
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_install }}"
  ignore_errors: true
  tags:
    - brew
  async: 300
  poll: 0

- name: Remove brew package(s)
  community.general.homebrew:
    name: "{{ item }}"
    state: absent
  with_items: "{{ brew_uninstall }}"
  tags:
    - brew
  async: 300
  poll: 0
