---
# tasks file for tmux
- name: Tmux Package Manager
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: ~/.tmux/plugins/tpm
    force: true
  tags:
    - tmux
    - always

- name: Copy tmux config
  ansible.builtin.copy:
    src: tmux/tmux.conf
    dest: ~/.tmux.conf
    owner: "{{ ansible_user_id }}"
    mode: '0644'
  tags:
    - tmux
    - always

- name: Copy tmux script
  ansible.builtin.copy:
    src: tmux/tmux.sh
    dest: ~/.config/tmux.sh
    owner: "{{ ansible_user_id }}"
    mode: '0744'
  tags:
    - tmux
    - always
