# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

autoload -U colors && colors

## History
HISTSIZE=10000
SAVEHIST=10000

# Path to your oh-my-zsh installation.
plugins=(
  git
  ansible
  docker
  kubectl
  terraform
  bundler
  dotenv
  rake
  rbenv
  ruby
  zsh-syntax-highlighting
  zsh-autosuggestions
)
export ZSH="$HOME/.oh-my-zsh"
prompt_context () { }

source ~/.oh-my-zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_THEME="agnoster"

CASE_SENSITIVE="true"

source $ZSH/oh-my-zsh.sh

# User configuration

# Preferred editor for local and remote sessions
export EDITOR='nvim'

# Set personal aliases, overriding those provided by oh-my-zsh libs,
alias cls="clear"
alias k=kubectl
alias ks="k9s"

alias v="nvim"
alias vim="nvim"

alias watch="viddy"

alias zz="caffeinate -d"

alias cp='cp -iv'                           # Preferred 'cp' implementation
alias mv='mv -iv'                           # Preferred 'mv' implementation
alias mkdir='mkdir -pv'                     # Preferred 'mkdir' implementation
alias del='rm -rfv'
alias ll='ls -FGlAhp'                       # Preferred 'ls' implementation
alias less='less -FSRXc'                    # Preferred 'less' implementation
alias cic='set completion-ignore-case On'   # cic:          Make tab-completion case-insensitive


###KUBE_PS1_SOURCE###
PS1='$(kube_ps1)'$PS1
KUBE_PS1_SYMBOL_DEFAULT=''
KUBE_PS1_SEPARATOR=''
KUBE_PS1_SUFFIX=' - '
KUBE_PS1_PREFIX=''

alias kns='kubens'

# terraform fun
alias tfp='terraform plan -out plan'
alias tfa='terraform apply plan'
alias tfd='terraform destroy -auto-approve'
alias tfi='terraform init'
alias tfc='docker run -it --rm -m 2048m --cpus=2 -v $(pwd):/tmp -v ~/.aws:/root/.aws --entrypoint sh terraform'

# work dirs
alias work='cd ~/work'

# cloud directories
alias cld='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs/'

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform

## krew
export PATH="${PATH}:${HOME}/.krew/bin"

## direnv
eval "$(direnv hook zsh)"

## tmuxs
alias tm="~/.config/new-windows.sh"
alias ts="~/.config/new-session.sh"


export KICS_QUERIES_PATH=/usr/local/opt/kics/share/kics/assets/queries

###P10K_SOURCE###

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# go
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
# Homebrew
export GOROOT="$(brew --prefix golang)/libexec"
# Manual install
# export GOROOT=/usr/local/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

export KICS_QUERIES_PATH=/usr/local/opt/kics/share/kics/assets/queries

export FAV_SE="google"

## dive cli
alias dive="docker run -ti --rm  -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive"


## stupid tf
alias tp="just clean && just local init && just local plan"
alias tf="just clean && just init && just plan"

# cf
export CLOUDFLARE_API_KEY="4dca22d44cbba15818a726cc740a51218e56c"
export CLOUDFLARE_EMAIL="oscar.rodriguez@ro.co"

# claude
export OP_BIOMETRIC_UNLOCK_ENABLED=true
