name: Linters

on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    container:
      image: cytopia/ansible-lint

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Run ansible lint
        run: ansible-lint -x command-instead-of-shell -x no-changed-when -x git-latest
