name: Linters

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Install ansible
        run: apt-get update && apt-get install -qy ansible

      - name: List dir files
        run: ls

      - name: Run ansible lint
        run: ansible-lint .
