name: Linters

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: List dir files
        run: ls

      - name: Run ansible lint
        uses: cytopia/ansible-lint@latest
