name: Linters

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: cytopia/ansible-lint@latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: List dir files
        run: ls

      - name: Run ansible lint
        run: ansible-lint .
